download_images:
	# Link to large image in OneDrive
	wget --no-check-certificate "https://ycv2oq.db.files.1drv.com/y4mbI5BW85A-EEtUABeBsLLiznFrXBDu6Kr2lvjTG9ec-X9Qmthom_kvufjz-renXArC2VbCdDHvJ88UNqWvQioPAp1obhtIgVFsGIA4Nu_d-RUegq3Shz-S5Ickn9oS6pmBb24wsTuQ4bCmUAlXmvIOokdy8vPk-S7qvKu_EdjVoJoCZtq9mXCDgzcCuf09m3FDVIJFqWkWIbB_SCaGmXvtA" -O img.jpg