download_images:
	# Link to large image in OneDrive
	wget --no-check-certificate "https://onedrive.live.com/download?cid=657C60FA38653333&resid=657C60FA38653333%21417444&authkey=ACBWzz2JmRIglk8" -O img.png