download_images:
	# Link to large image in OneDrive
	wget --no-check-certificate "https://upfrrg.db.files.1drv.com/y4mQH691HdXYT8BoKD0nfGSqcOqULBYrRYs6lGZjOJ6YgjGNMjopbTTo1ZOj95Ai83-A7XsfHQEe9BxjqxOiXZTj0ULBoBHyEzCo6NTobyFos-NaCRkjLD-OI6Y057u7l8rOTOyfqJCVKBrZNJXI3vWlNp1Rxs3W_lpEwzzuu7rdB91Q50FdtEzYaBm-8wXyyQ3m7sAMOu3c_Yigv3wB_ThfA" -O img.png